server:
  servlet:
    context-path: /cms
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    include: mapper
    active: dev
  application:
    # 本服务注册到注册到服务器的名称, 这个名称就是后面调用服务时的服务标识符
    name: hr-admin
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

---
server:
  port: 7002
spring:
  profiles: dev
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379
#设置服务注册中心的URL，本服务要向该服务注册中心注册自己
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7003/eureka
    register-with-eureka: false
    fetch-registry: false

---
server:
  port: 8002
spring:
  profiles: uat
#设置服务注册中心的URL，本服务要向该服务注册中心注册自己（集群服务中心）
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8003/eureka
---
server:
  port: 9002
spring:
  profiles: prod
#设置服务注册中心的URL，本服务要向该服务注册中心注册自己（集群服务中心）
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9003/eureka